<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://raw.githubusercontent.com/anandhakryshnan/anandhakryshnan/output/pacman-contribution-graph-dark.svg">
  <img alt="pacman contribution graph" src="https://raw.githubusercontent.com/anandhakryshnan/anandhakryshnan/output/pacman-contribution-graph.svg">
</picture>
